#!/bin/sh

sudo apt update && sudo apt upgrade -y && sudo do-release-upgrade && sudo apt-get --with-new-pkgs upgrade

sudo apt autoremove

lsb_release -a

do-release-upgrade

sudo aptitude safe-upgrade

lsb_release -d
